# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ainotes
author: Baptiste Pesquet
logo: logo.png
copyright: 2023-present
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns : [_build, "**.DS_Store", "**.ipynb_checkpoints", ".venv", "**/simple_*.ipynb", 
  "**calculus.ipynb", "**linear_algebra.ipynb", "**human_brain.md", "**cognitive_science.md",
  "**_solution.ipynb"]

# Configure re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: pyfit.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/bpesquet/ainotes  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar

sphinx:
  config:
    bibtex_reference_style: author_year